import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generateInvoicePDF = (invoice, t) => {
  try {
    const doc = new jsPDF();
    
    const safeT = (key, fallback) => {
      try {
        if (typeof t !== 'function') return fallback;
        const val = t(key);
        return (typeof val === 'string') ? val : fallback;
      } catch (e) { return fallback; }
    };

    const currency = invoice.currency || '$';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(66, 185, 131);
    doc.text(safeT('invoice', 'INVOICE'), 105, 20, { align: "center" });

    // Info
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text(`${safeT('customer', 'Customer')}: ${invoice.clientName || 'N/A'}`, 15, 40);
    doc.text(`${safeT('date', 'Date')}: ${invoice.date || new Date().toLocaleDateString()}`, 15, 48);
    doc.text(`ID: INV-${(invoice.id || Date.now()).toString().slice(-6)}`, 15, 56);

    // Items Table
    const tableConfig = {
      startY: 65,
      head: [[
        safeT('itemName', 'Item'), 
        safeT('quantity', 'Qty'), 
        safeT('price', 'Price'), 
        safeT('total', 'Total')
      ]],
      body: (invoice.items || []).map(item => [
        item.name || "Item",
        `${item.quantity}`,
        `${currency} ${Number(item.price).toLocaleString()}`,
        `${currency} ${(Number(item.quantity) * Number(item.price)).toLocaleString()}`
      ]),
      headStyles: { fillColor: [66, 185, 131] },
      alternateRowStyles: { fillColor: [245, 245, 245] }
    };

    if (typeof doc.autoTable === 'function') {
      doc.autoTable(tableConfig);
    } else {
      autoTable(doc, tableConfig);
    }

    let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 100;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${safeT('total', 'Total')}: ${currency} ${Number(invoice.total || 0).toLocaleString()}`, 15, finalY);

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(safeT('thankYou', 'Thank you for choosing us!'), 105, 280, { align: "center" });

    doc.save(`Invoice_${invoice.id || Date.now()}.pdf`);
    return true;
  } catch (error) {
    console.error("PDF EXCEPTION:", error);
    alert("Could not generate PDF. Please try again.");
    throw error;
  }
};

export const generateDailyReportPDF = (invoices, dateString, t) => {
  try {
    const doc = new jsPDF();
    const safeT = (key, fallback) => {
      try {
        if (typeof t !== 'function') return fallback;
        const val = t(key);
        return (typeof val === 'string') ? val : fallback;
      } catch (e) { return fallback; }
    };

    doc.setFontSize(22);
    doc.setTextColor(66, 185, 131);
    doc.text(safeT('dailyReport', 'DAILY SALES REPORT'), 105, 20, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text(`${safeT('date', 'Date')}: ${dateString}`, 15, 35);
    doc.text(`${safeT('totalTransactions', 'Total Transactions')}: ${invoices.length}`, 15, 42);

    const tableConfig = {
      startY: 50,
      head: [[
        safeT('date', 'Date'), 
        safeT('customer', 'Client'), 
        safeT('total', 'Total')
      ]],
      body: invoices.map(inv => [
        inv.date,
        inv.clientName,
        `${inv.currency || '$'} ${Number(inv.total || 0).toLocaleString()}`
      ]),
      headStyles: { fillColor: [66, 185, 131] },
      alternateRowStyles: { fillColor: [245, 245, 245] }
    };

    if (typeof doc.autoTable === 'function') {
      doc.autoTable(tableConfig);
    } else {
      autoTable(doc, tableConfig);
    }

    let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 100;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${safeT('grandTotals', 'Grand Totals')}:`, 15, finalY);
    
    const grandTotal = invoices.reduce((sum, inv) => sum + Number(inv.total || 0), 0);
    doc.text(`${grandTotal.toLocaleString()}`, 20, finalY + 8);

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(safeT('generatedBy', 'Generated by Invoxa'), 105, 280, { align: "center" });

    doc.save(`Daily_Report_${dateString.replace(/\//g, '-')}.pdf`);
    return true;
  } catch (error) {
    console.error("REPORT EXCEPTION:", error);
    throw error;
  }
};
