import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { profileStore } from "@/store/userProfileStore";

import { notificationStore } from "@/store/notificationStore";

export const generateInvoicePDF = (invoice, t) => {
  try {
    const doc = new jsPDF();
    const profile = profileStore.profile;
    
    // Safety check for critical fields
    if (!invoice || !invoice.clientName) {
      console.warn("PDF Warning: Missing client name, using fallback.");
    }
    
    const clientName = invoice?.clientName || 'Valued Customer';
    const invoiceId = (invoice?.id || Date.now()).toString().slice(-6).toUpperCase();

    const safeT = (key, fallback) => {
      try {
        if (typeof t !== 'function') return fallback;
        const val = t(key);
        return (typeof val === 'string') ? val : fallback;
      } catch (e) { return fallback; }
    };

    const currency = invoice.currency || profile.currency || '$';

    // 1. Professional Header
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(28);
    doc.setTextColor(34, 197, 94); // Premium Green
    doc.setFont("helvetica", "bold");
    doc.text(safeT('invoice', 'INVOICE'), 105, 25, { align: "center" });

    // 2. Business & Client Info Grid
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text("FROM:", 15, 50);
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(profile.businessName || "INVOXA SMART SOLUTIONS", 15, 56);
    doc.setFontSize(10);
    doc.text(`Email: ${profile.email || 'support@invoxa.com'}`, 15, 62);
    doc.text(`Contact: ${profile.phone || '+250 XXX XXX XXX'}`, 15, 68);
    if (profile.address) {
      doc.text(`Address: ${profile.address}`, 15, 74);
    }

    doc.setTextColor(100, 100, 100);
    doc.text("BILL TO:", 120, 50);
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(clientName, 120, 56);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`${safeT('date', 'Date')}: ${invoice.date || new Date().toLocaleDateString()}`, 120, 62);
    doc.text(`Invoice ID: #${invoiceId}`, 120, 68);

    // 3. Items Table with Unit Column
    const tableConfig = {
      startY: profile.address ? 85 : 80,
      head: [[
        safeT('itemName', 'Item Description'), 
        safeT('quantity', 'Qty'), 
        safeT('unit', 'Unit'),
        safeT('price', 'Price'), 
        safeT('total', 'Total')
      ]],
      body: (invoice.items || []).map(item => [
        item.name || "Item",
        item.quantity || "1",
        item.unit || "pcs",
        `${currency} ${Number(item.price || 0).toLocaleString()}`,
        `${currency} ${(Number(item.quantity || 0) * Number(item.price || 0)).toLocaleString()}`
      ]),
      headStyles: { fillColor: [34, 197, 94], fontSize: 11, halign: 'center' },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { halign: 'center' },
        2: { halign: 'center' },
        3: { halign: 'right' },
        4: { halign: 'right' }
      },
      alternateRowStyles: { fillColor: [250, 255, 251] },
      margin: { left: 15, right: 15 }
    };

    if (typeof doc.autoTable === 'function') {
      doc.autoTable(tableConfig);
    } else {
      autoTable(doc, tableConfig);
    }

    let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;

    // 4. Summary & Payment Info Section
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(safeT('bankDetails', 'PAYMENT INFORMATION'), 15, finalY);
    doc.setFontSize(10);
    doc.text(`${safeT('bankName', 'Bank Name')}: ${profile.bankName || 'N/A'}`, 15, finalY + 7);
    doc.text(`${safeT('accountNumber', 'Account No')}: ${profile.accountNumber || 'N/A'}`, 15, finalY + 13);
    doc.text(`${safeT('paidSuccess', 'Payment Status')}: PAID`, 15, finalY + 19);

    // Total Block
    doc.setFillColor(34, 197, 94);
    doc.rect(130, finalY - 5, 65, 25, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(safeT('total', 'GRAND TOTAL'), 135, finalY + 2);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`${currency} ${Number(invoice.total || 0).toLocaleString()}`, 135, finalY + 12);

    // 5. Signature Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text("__________________________", 140, 260);
    doc.text(safeT('spec', 'Authorized Signature'), 145, 265);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(safeT('thankYou', 'Thank you for choosing us!'), 105, 280, { align: "center" });
    doc.setFont("helvetica", "italic");
    doc.text(safeT('generatedBy', 'Generated by Invoxa'), 105, 285, { align: "center" });

    doc.save(`Invoice_${clientName.replace(/\s+/g, '_')}_${invoiceId}.pdf`);
    return true;
  } catch (error) {
    console.error("PDF EXCEPTION:", error);
    notificationStore.error("Could not generate PDF. Please try again.");
    throw error;
  }
};

export const generateDailyReportPDF = (invoices, dateString, t) => {
  try {
    const doc = new jsPDF();
    const safeT = (key, fallback) => {
      try {
        if (typeof t !== 'function') return fallback;
        const val = t(key);
        return (typeof val === 'string') ? val : fallback;
      } catch (e) { return fallback; }
    };

    doc.setFontSize(22);
    doc.setTextColor(66, 185, 131);
    doc.text(safeT('dailyReport', 'DAILY SALES REPORT'), 105, 20, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text(`${safeT('date', 'Date')}: ${dateString}`, 15, 35);
    doc.text(`${safeT('totalTransactions', 'Total Transactions')}: ${invoices.length}`, 15, 42);

    const tableConfig = {
      startY: 50,
      head: [[
        safeT('date', 'Date'), 
        safeT('customer', 'Client'), 
        safeT('total', 'Total')
      ]],
      body: invoices.map(inv => [
        inv.date,
        inv.clientName,
        `${inv.currency || '$'} ${Number(inv.total || 0).toLocaleString()}`
      ]),
      headStyles: { fillColor: [66, 185, 131] },
      alternateRowStyles: { fillColor: [245, 245, 245] }
    };

    if (typeof doc.autoTable === 'function') {
      doc.autoTable(tableConfig);
    } else {
      autoTable(doc, tableConfig);
    }

    let finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 100;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${safeT('grandTotals', 'Grand Totals')}:`, 15, finalY);
    
    const grandTotal = invoices.reduce((sum, inv) => sum + Number(inv.total || 0), 0);
    doc.text(`${grandTotal.toLocaleString()}`, 20, finalY + 8);

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(safeT('generatedBy', 'Generated by Invoxa'), 105, 280, { align: "center" });

    doc.save(`Daily_Report_${dateString.replace(/\//g, '-')}.pdf`);
    return true;
  } catch (error) {
    console.error("REPORT EXCEPTION:", error);
    throw error;
  }
};
